# Generated by Django 5.1.7 on 2025-03-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meditation_api", "0002_remove_dailyexperience_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeditationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meditation_type", models.CharField(max_length=100)),
                ("duration_minutes", models.IntegerField()),
                ("how_to_perform", models.TextField()),
                ("benefits", models.TextField(blank=True, null=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="meditation_api.dailyexperience",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MeditationSuggestion",
        ),
    ]
