# Generated by Django 5.1.4 on 2024-12-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "diet_recommendation",
            "0003_rename_country_userprofile_activity_level_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="food_type",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Target_timeline",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Food_type",
            field=models.CharField(default="Not Specified", max_length=20),
        ),
    ]
