# Generated by Django 5.0.1 on 2025-01-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "Food_type",
                    models.CharField(
                        choices=[
                            ("VEG", "Vegetarian"),
                            ("NVEG", "Non-Vegetarian"),
                            ("VEGAN", "Vegan"),
                        ],
                        max_length=5,
                    ),
                ),
                ("goal", models.CharField(max_length=200)),
                ("disease", models.TextField(blank=True)),
                ("allergics", models.TextField(blank=True)),
                ("Target_timeline", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DietRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_text", models.TextField()),
                ("bmi", models.FloatField()),
                ("bmi_category", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diet_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
